name: booking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  card_swiper: ^3.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  vertical_card_pager: ^1.5.0
  flicked_cards: ^0.0.3
  google_fonts: ^5.1.0
  calendar_view: ^1.0.4
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.1
  calendar_date_picker2: ^0.5.3
  flutter_week_view: ^1.3.0
  vector_math: ^2.1.4
  animated_digit: ^3.2.3
  wheel_slider: ^1.1.1
  scroll_snap_list: ^0.9.1
  flutter_staggered_grid_view: ^0.7.0
  assorted_layout_widgets: ^8.0.4
  word_cloud: ^1.0.1
  flutter_scatter: ^0.2.0
  fluid_bottom_nav_bar: ^1.4.0
  flutter_analog_clock: ^1.0.3
  html_editor_enhanced: ^2.5.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/
    - assets/img/
    - assets/img/shoes/
    - assets/img/superheroes/
  uses-material-design: true

